import React, { createContext, useContext, useState, useEffect, useCallback } from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

export type LangCode = "ko" | "en" | "vi" | "th" | "fil" | "uz" | "id";

export const LANGUAGES: { code: LangCode; nativeName: string; flag: string }[] = [
  { code: "ko", nativeName: "한국어", flag: "🇰🇷" },
  { code: "en", nativeName: "English", flag: "🇺🇸" },
  { code: "vi", nativeName: "Tiếng Việt", flag: "🇻🇳" },
  { code: "th", nativeName: "ภาษาไทย", flag: "🇹🇭" },
  { code: "fil", nativeName: "Filipino", flag: "🇵🇭" },
  { code: "uz", nativeName: "O'zbek", flag: "🇺🇿" },
  { code: "id", nativeName: "Bahasa Indonesia", flag: "🇮🇩" },
];

export const LANG_NAMES_FOR_AI: Record<LangCode, string> = {
  ko: "Korean",
  en: "English",
  vi: "Vietnamese",
  th: "Thai",
  fil: "Filipino",
  uz: "Uzbek",
  id: "Indonesian",
};

type T = Record<string, string>;

const translations: Record<LangCode, T> = {
  ko: {
    save: "저장", cancel: "취소", confirm: "확인", error: "오류",
    loading: "로딩 중", done: "완료", required: "필수", optional: "선택",
    back: "뒤로", close: "닫기", select: "선택", language: "언어",
    login_userId: "아이디", login_password: "패스워드", login_btn: "로그인",
    login_register: "회원가입", login_noAccount: "계정이 없으신가요?",
    login_errorEmpty: "아이디와 패스워드를 입력해주세요.",
    login_errorInvalid: "아이디 또는 패스워드가 올바르지 않습니다.",
    reg_title: "회원가입", reg_name: "이름", reg_role: "역할",
    reg_courseName: "과정명", reg_courseNameRequired: "교육생은 과정명을 입력해야 합니다.", reg_confirmPw: "패스워드 확인",
    reg_profilePhoto: "프로필 사진",
    reg_errorRequired: "아이디, 패스워드, 이름은 필수 항목입니다.",
    reg_errorPwMatch: "패스워드가 일치하지 않습니다.",
    reg_errorPwLength: "패스워드는 4자 이상이어야 합니다.",
    reg_errorDuplicate: "이미 사용 중인 아이디입니다.",
    role_trainee: "교육생", role_teacher: "교사", role_admin: "관리자",
    nav_gallery: "갤러리", nav_diagnosis: "랭킹", nav_coaching: "AI 실시간 코칭",
    home_hello: "안녕하세요",
    home_title: "어떤 학습을 시작할까요?",
    home_subtitle: "학습 모드를 선택해주세요",
    home_theory: "이론학습",
    home_theoryDesc: "오늘의 학습 · OX 퀴즈 게임",
    home_skill: "기량향상",
    home_skillDesc: "AI 실시간 코칭 · 갤러리 · 랭킹",
    theory_subtitle: "학습 종류를 선택해주세요",
    theory_today: "오늘의 학습",
    theory_today_desc: "매일 새로운 3문제",
    theory_review: "복습하기",
    theory_ox: "OX 퀴즈 게임",
    theory_ox_desc: "최고 웨이브에 도전",
    theory_difficulty: "난이도",
    theory_next: "다음",
    theory_submit: "제출하기",
    theory_finish: "학습완료",
    theory_correct: "정답",
    theory_wrong: "오답",
    theory_my_answer: "내 답",
    theory_correct_answer: "정답",
    theory_explanation: "해설",
    theory_score_today: "오늘의 점수",
    theory_no_data: "데이터가 없습니다",
    theory_must_answer_all: "모든 문제에 답해주세요.",
    theory_submit_error: "제출 중 오류가 발생했습니다.",
    theory_pdf_title: "이론학습 이력 PDF",
    ox_title: "OX 퀴즈 게임",
    ox_hero: "OX 챌린지",
    ox_hero_desc: "용접 이론 OX로 최고 웨이브에 도전!",
    ox_ranking_title: "최고 기록 랭킹",
    ox_ranking_empty: "아직 기록이 없습니다",
    ox_start: "게임 시작",
    ox_accuracy: "정답률",
    ox_resume: "이어하기",
    ox_start_new: "처음부터 시작",
    ox_gameover_title: "SYSTEM FAILURE",
    ox_quit_title: "GAME ABORTED",
    ox_gameover_sub: "기지가 파괴되었습니다",
    ox_final_wave: "최종 도달 웨이브",
    ox_quiz_score: "퀴즈 점수",
    ox_retry: "다시하기",
    ox_exit: "나가기",
    gallery_empty: "아직 분석 결과가 없습니다",
    gallery_upload: "용접 사진을 업로드하여\n첫 번째 AI 진단을 받아보세요",
    gallery_new: "새 분석",
    photo_title: "용접 사진 등록",
    photo_front: "정면 사진", photo_side: "측면 사진", photo_back: "이면 사진",
    photo_frontDesc: "캡패스 정면 (필수)", photo_sideDesc: "비드 높이 측정용 (선택)",
    photo_backDesc: "루트패스 확인용 (선택)",
    photo_addPhoto: "사진 추가", photo_changePhoto: "사진 변경",
    photo_camera: "카메라", photo_gallery: "갤러리",
    photo_analyzeBtn: "AI 분석 시작",
    photo_analyzing: "AI가 용접 품질을 분석 중...",
    photo_weldProcess: "용접 공정", photo_weldPosture: "용접 자세",
    photo_weldMaterial: "소재", photo_selfScore: "자체 점수",
    photo_thickness: "부재 두께 (mm)",
    photo_required: "정면 사진은 필수입니다.",
    photo_scoreError: "자체 점수를 0~100 사이로 입력해주세요.",
    photo_selfScoreHint: "자체 점수 (0~100)",
    diag_aiScore: "AI평가점수", diag_beadAnalysis: "비드 분석",
    diag_defectEval: "결함 평가", diag_aiReport: "AI 종합 진단 리포트",
    diag_heatmap: "시각적 분석 (히트맵)", diag_selfCompare: "자체 평가 비교",
    diag_improvements: "AI 개선 제안 및 훈련 가이드",
    diag_improvementMulti: "{n}회 평가 결과를 종합한 맞춤형 훈련 가이드",
    diag_improvementSingle: "이번 평가 결과 기반 훈련 가이드",
    diag_trend: "누적 트렌드 분석", diag_history: "전체 결과 이력",
    diag_pass: "합격", diag_fail: "불합격", diag_grade: "등급",
    diag_defectName: "결함", diag_measured: "측정값", diag_standard: "기준",
    diag_deduction: "차감점수", diag_showMarkers: "결함위치 표시",
    diag_hideMarkers: "결함위치 숨김",
    diag_confidence: "AI 판단 확신도", diag_avgScore: "토탈 평균점수",
    diag_bestScore: "역대최고점수", diag_totalEvals: "AI 평가 완료",
    diag_recentGrade: "최근 등급",
    diag_overallVerdict: "종합 판정", diag_top3: "주요 결함 Top 3",
    diag_noDefect: "결함 없음 - 우수한 용접 품질!",
    bead_width: "비드 폭 균일성", bead_height: "비드 높이 균일성",
    bead_filletSize: "각장/각목", bead_straightness: "비드 직진도", bead_pitch: "피치 균일도",
    label_process: "용접 공정", label_posture: "용접 자세", label_material: "재료/형상",
    points_suffix: "점",
    rank_title: "AI 진단 순위", rank_subtitle: "누적 평균점수 기준",
    rank_total: "전체", rank_weekly: "주간", rank_daily: "오늘",
    rank_myRank: "내 순위", rank_topRiser: "최고 상승", rank_topFaller: "최고 하락",
    rank_empty: "결과물 없음", rank_noData: "아직 등록된 결과물이 없습니다",
    rank_upload: "업로드", rank_best: "최고", rank_avg: "평균",
    logout: "로그아웃",
    nav_members: "회원관리",
    result_notFound: "결과를 찾을 수 없습니다",
    diag_outOf100: "/ 100점",
    diag_aiSummary: "AI 종합 분석",
    diag_historyReflected: "(총 {n}회 이력 반영)",
    diag_sideAnalyzing: "측면 사진이 업로드되지 않았습니다",
    diag_backAnalyzing: "이면 사진이 업로드되지 않았습니다",
    diag_sideNoData: "측면 사진이 업로드되지 않았습니다",
    diag_backNoData: "이면 사진이 업로드되지 않았습니다",
    diag_sideNotDetected: "측면 사진에서 비드가 식별되지 않아 측정값을 계산할 수 없습니다. 사진을 다시 촬영해주세요.",
    diag_backNotDetected: "이면 사진에서 비드가 식별되지 않아 측정값을 계산할 수 없습니다. 사진을 다시 촬영해주세요.",
    diag_noDefectsDetected: "이 사진에서 검출된 결함이 없습니다.",
    diag_coordsLoading: "좌표 데이터 준비 중",
    diag_noDefectAi: "AI 감지 결함 없음",
    diag_zoomHint: "핀치: 확대 · 확대 후 드래그 · 더블탭: 초기화",
    diag_noPhoto: "사진 없음",
    diag_beadStackTitle: "비드 쌓기 모드",
    diag_beadStackMsg: "비드 쌓기는 결함을 평가하지 않습니다.",
    diag_deviation: "이탈",
    diag_straightnessLabel: "직진도",
    diag_widthLabel: "폭",
    diag_beadType: "비드 형태",
    diag_selfScore: "자체 점수",
    diag_atLeast2: "2회 이상 평가를 받으면 트렌드 그래프가 표시됩니다",
    trend_totalAvg: "총 {n}회 평균",
    trend_skill: "기량 추세",
    trend_improved: "▲ 향상 (+{n}점)",
    trend_declined: "▼ 하락 ({n}점)",
    trend_vsPrev: "직전 대비",
    trend_currentResult: "현재 보는 결과",
    adm_deleteTitle: "결과물 삭제",
    adm_deleteConfirm: "{name}의 결과물을 삭제하시겠습니까?",
    adm_delete: "삭제",
    adm_savedTitle: "저장 완료",
    adm_savedMsg: "피드백이 저장되었습니다.\nAI가 다음 분석부터 이 기준을 적용합니다.",
    adm_saveFailed: "피드백 저장에 실패했습니다.",
    adm_networkErr: "네트워크 오류가 발생했습니다.",
    adm_feedbackTitle: "AI 분석 피드백",
    adm_feedbackDesc: "AI가 잘못 분석한 내용을 작성해주세요.\n저장된 피드백은 이후 모든 분석에 즉시 반영됩니다.",
    adm_target: "대상",
    adm_feedbackPlaceholder: "예: 스패터로 표시된 부분은 실제 오버랩입니다. 비드 가장자리에서 금속이 흘러넘친 경우를 스패터와 혼동하지 말 것.",
    adm_saveSubmit: "저장 및 AI 반영",
    cm_comments: "댓글",
    cm_empty: "아직 댓글이 없습니다. 첫 번째 댓글을 남겨보세요!",
    cm_reply: "답글",
    cm_replyTo: "{name}에게 답글",
    cm_inputPlaceholder: "댓글을 입력하세요...",
    cm_replyInputPlaceholder: "{name}에게 답글...",
    cm_deleteTitle: "댓글 삭제",
    cm_deleteConfirm: "이 댓글을 삭제하시겠습니까?",
    cm_addFailed: "댓글 등록에 실패했습니다.",
    cm_deleteFailed: "댓글 삭제에 실패했습니다.",
    cm_justNow: "방금 전",
    cm_minAgo: "{n}분 전",
    cm_hourAgo: "{n}시간 전",
    cm_dayAgo: "{n}일 전",
    reg_registrant: "등록자",
    reg_courseUnset: "과정 미지정",
    reg_photoSection: "사진 등록",
    reg_photoHint: "30mm 아루코(ArUco) 마커를 비드 옆에 함께 놓고 촬영해야 정확한 치수 분석이 가능합니다",
    reg_change: "변경",
    reg_plateThickness: "판재 두께",
    reg_pipeOuterDiameter: "배관 외경",
    reg_pipeSpec: "규격표",
    reg_aiAnalyzingDefault: "AI 분석 중...",
    reg_submitBtn: "등록 및 AI 분석",
    reg_pipeGuideTitle: "배관 외경 규격표",
    reg_pipeHelp: "호칭을 누르면 외경(mm)이 자동 입력됩니다.",
    reg_pipeFootnote: "※ 250A·300A는 일반 강관과 스테인리스 강관의 외경이 다릅니다.",
    reg_photoGuideTitle: "촬영 예시",
    stage_preparing: "📸 사진 준비 중...",
    stage_uploading: "📤 서버로 사진 전송 중...",
    stage_detecting: "🔍 Roboflow 결함 검출 중...",
    stage_measuring: "📐 비드 치수·직진도 계산 중...",
    stage_aiAnalyzing: "🤖 {model} 비드 형상 분석 중...",
    stage_writingReport: "📝 종합 진단 리포트 작성 중...",
    stage_finalizing: "✨ 결과 정리 중...",
    camera_webMsg: "카메라는 모바일 기기에서 사용하세요.",
    camera_permNeeded: "카메라 권한이 필요합니다",
    camera_permAllow: "권한 허용",
    camera_arucoInstr: "ArUco 마커를 우측 상단\n노란 가이드에 맞추고 수평으로 유지하세요",
    login_appTitle: "AI 용접 교육 플랫폼",
    login_today: "오늘",
    ai_analysisError: "AI 분석 중 오류가 발생했습니다. 다시 시도해주세요.",
    photo_reuploadTitle: "사진을 다시 업로드해 주세요",
    analysis_errorTitle: "분석 오류",
    conf_high: "사진이 선명하고 측정 기준이 잘 포함되어 있어 높은 신뢰도로 분석했습니다.",
    conf_med: "대부분의 항목이 명확하게 분석되었으나, 일부 측정값은 추정을 포함할 수 있습니다.",
    conf_low: "사진 해상도·조명·촬영 각도로 인해 일부 항목의 정확도가 제한됩니다. 줄자가 포함된 사진이나 다양한 각도의 사진을 추가하면 정확도가 향상됩니다.",
    conf_verylow: "사진 품질 또는 각도 문제로 정확한 분석이 어려웠습니다. 더 선명한 사진과 측면·이면 사진, 줄자를 함께 촬영하시면 신뢰도가 크게 향상됩니다.",
    compare_accurate: "정확한 자기 평가",
    compare_under: "자신을 과소평가하고 있습니다",
    compare_over: "자신을 과대평가하고 있습니다",
  },
  en: {
    save: "Save", cancel: "Cancel", confirm: "Confirm", error: "Error",
    loading: "Loading", done: "Done", required: "Required", optional: "Optional",
    back: "Back", close: "Close", select: "Select", language: "Language",
    login_userId: "Username", login_password: "Password", login_btn: "Login",
    login_register: "Register", login_noAccount: "Don't have an account?",
    login_errorEmpty: "Please enter username and password.",
    login_errorInvalid: "Invalid username or password.",
    reg_title: "Register", reg_name: "Name", reg_role: "Role",
    reg_courseName: "Course Name", reg_courseNameRequired: "Trainees must enter a course name.", reg_confirmPw: "Confirm Password",
    reg_profilePhoto: "Profile Photo",
    reg_errorRequired: "Username, password, and name are required.",
    reg_errorPwMatch: "Passwords do not match.",
    reg_errorPwLength: "Password must be at least 4 characters.",
    reg_errorDuplicate: "Username already in use.",
    role_trainee: "Trainee", role_teacher: "Instructor", role_admin: "Admin",
    nav_gallery: "Gallery", nav_diagnosis: "Ranking", nav_coaching: "AI Live Coaching",
    home_hello: "Hello",
    home_title: "What would you like to learn?",
    home_subtitle: "Choose a learning mode",
    home_theory: "Theory",
    home_theoryDesc: "Daily quiz · OX game",
    home_skill: "Skill Up",
    home_skillDesc: "AI diagnosis · Gallery · Ranking",
    theory_subtitle: "Choose a learning type",
    theory_today: "Today's Lesson",
    theory_today_desc: "3 new questions every day",
    theory_review: "Review",
    theory_ox: "OX Quiz Game",
    theory_ox_desc: "Aim for the highest wave",
    theory_difficulty: "Difficulty",
    theory_next: "Next",
    theory_submit: "Submit",
    theory_finish: "Done",
    theory_correct: "Correct",
    theory_wrong: "Wrong",
    theory_my_answer: "My answer",
    theory_correct_answer: "Correct",
    theory_explanation: "Explanation",
    theory_score_today: "Today's Score",
    theory_no_data: "No data",
    theory_must_answer_all: "Please answer all questions.",
    theory_submit_error: "Submission failed.",
    theory_pdf_title: "Theory History PDF",
    ox_title: "OX Quiz Game",
    ox_hero: "OX Challenge",
    ox_hero_desc: "Challenge yourself to reach the highest wave!",
    ox_ranking_title: "Top Wave Ranking",
    ox_ranking_empty: "No records yet",
    ox_start: "Start Game",
    ox_accuracy: "Accuracy",
    ox_resume: "Resume",
    ox_start_new: "Start Fresh",
    ox_gameover_title: "SYSTEM FAILURE",
    ox_quit_title: "GAME ABORTED",
    ox_gameover_sub: "The base has been destroyed",
    ox_final_wave: "Final Wave",
    ox_quiz_score: "Quiz Score",
    ox_retry: "Retry",
    ox_exit: "Exit",
    gallery_empty: "No analysis results yet",
    gallery_upload: "Upload a welding photo to get\nyour first AI diagnosis",
    gallery_new: "New Analysis",
    photo_title: "Register Welding Photo",
    photo_front: "Front Photo", photo_side: "Side Photo", photo_back: "Back Photo",
    photo_frontDesc: "Cap pass front (required)",
    photo_sideDesc: "For bead height measurement (optional)",
    photo_backDesc: "For root pass inspection (optional)",
    photo_addPhoto: "Add Photo", photo_changePhoto: "Change Photo",
    photo_camera: "Camera", photo_gallery: "Gallery",
    photo_analyzeBtn: "Start AI Analysis",
    photo_analyzing: "AI is analyzing welding quality...",
    photo_weldProcess: "Welding Process", photo_weldPosture: "Welding Position",
    photo_weldMaterial: "Material", photo_selfScore: "Self Score",
    photo_thickness: "Material Thickness (mm)",
    photo_required: "Front photo is required.",
    photo_scoreError: "Please enter a self score between 0 and 100.",
    photo_selfScoreHint: "Self score (0~100)",
    diag_aiScore: "AI Score", diag_beadAnalysis: "Bead Analysis",
    diag_defectEval: "Defect Evaluation", diag_aiReport: "AI Comprehensive Report",
    diag_heatmap: "Visual Analysis (Heatmap)", diag_selfCompare: "Self Assessment Comparison",
    diag_improvements: "AI Improvement Suggestions",
    diag_improvementMulti: "Personalized training guide based on {n} evaluations",
    diag_improvementSingle: "Training guide based on this evaluation",
    diag_trend: "Cumulative Trend Analysis", diag_history: "Full Result History",
    diag_pass: "PASS", diag_fail: "FAIL", diag_grade: "Grade",
    diag_defectName: "Defect", diag_measured: "Measured", diag_standard: "Standard",
    diag_deduction: "Deduction", diag_showMarkers: "Show Defect Markers",
    diag_hideMarkers: "Hide Defect Markers",
    diag_confidence: "AI Confidence", diag_avgScore: "Avg Score",
    diag_bestScore: "Best Score", diag_totalEvals: "AI Evaluations",
    diag_recentGrade: "Recent Grade",
    diag_overallVerdict: "Overall Verdict", diag_top3: "Top 3 Defects",
    diag_noDefect: "No defects - Excellent weld quality!",
    bead_width: "Bead Width Uniformity", bead_height: "Bead Height Uniformity",
    bead_filletSize: "Fillet Leg Size", bead_straightness: "Bead Straightness", bead_pitch: "Pitch Uniformity",
    label_process: "Welding Process", label_posture: "Welding Position", label_material: "Material",
    points_suffix: " pts",
    rank_title: "AI Diagnosis Ranking", rank_subtitle: "Based on cumulative average score",
    rank_total: "All Time", rank_weekly: "Weekly", rank_daily: "Today",
    rank_myRank: "My Rank", rank_topRiser: "Top Riser", rank_topFaller: "Top Faller",
    rank_empty: "No Results", rank_noData: "No results registered yet",
    rank_upload: "uploads", rank_best: "Best", rank_avg: "Avg",
    logout: "Logout",
    nav_members: "Members",
    result_notFound: "Result not found",
    diag_outOf100: "/ 100 pts",
    diag_aiSummary: "AI Comprehensive Analysis",
    diag_historyReflected: "(reflecting {n} sessions of history)",
    diag_sideAnalyzing: "Side photo not uploaded",
    diag_backAnalyzing: "Back photo not uploaded",
    diag_sideNoData: "Side photo not uploaded",
    diag_backNoData: "Back photo not uploaded",
    diag_sideNotDetected: "Could not identify bead in side photo. Please retake the photo.",
    diag_backNotDetected: "Could not identify bead in back photo. Please retake the photo.",
    diag_noDefectsDetected: "No defects detected in this photo.",
    diag_coordsLoading: "Preparing coordinate data",
    diag_noDefectAi: "No defects detected by AI",
    diag_zoomHint: "Pinch: zoom · Drag when zoomed · Double tap: reset",
    diag_noPhoto: "No photo",
    diag_beadStackTitle: "Bead Stacking Mode",
    diag_beadStackMsg: "Bead stacking does not evaluate defects.",
    diag_deviation: "deviation",
    diag_straightnessLabel: "Straightness",
    diag_widthLabel: "Width",
    diag_beadType: "Bead Type",
    diag_selfScore: "Self Score",
    diag_atLeast2: "Trend graph appears after 2 or more evaluations",
    trend_totalAvg: "Average of {n} sessions",
    trend_skill: "Skill Trend",
    trend_improved: "▲ Improved (+{n} pts)",
    trend_declined: "▼ Declined ({n} pts)",
    trend_vsPrev: "vs previous",
    trend_currentResult: "Current result",
    adm_deleteTitle: "Delete Result",
    adm_deleteConfirm: "Delete {name}'s result?",
    adm_delete: "Delete",
    adm_savedTitle: "Saved",
    adm_savedMsg: "Feedback saved.\nAI will apply this standard from the next analysis.",
    adm_saveFailed: "Failed to save feedback.",
    adm_networkErr: "A network error occurred.",
    adm_feedbackTitle: "AI Analysis Feedback",
    adm_feedbackDesc: "Describe what the AI got wrong.\nSaved feedback will be applied to all subsequent analyses.",
    adm_target: "Target",
    adm_feedbackPlaceholder: "e.g.: The area marked as spatter is actually overlap. Do not confuse molten metal flowing over the bead edge with spatter.",
    adm_saveSubmit: "Save & Apply to AI",
    cm_comments: "Comments",
    cm_empty: "No comments yet. Be the first to leave one!",
    cm_reply: "Reply",
    cm_replyTo: "Reply to {name}",
    cm_inputPlaceholder: "Write a comment...",
    cm_replyInputPlaceholder: "Reply to {name}...",
    cm_deleteTitle: "Delete Comment",
    cm_deleteConfirm: "Delete this comment?",
    cm_addFailed: "Failed to post comment.",
    cm_deleteFailed: "Failed to delete comment.",
    cm_justNow: "just now",
    cm_minAgo: "{n}m ago",
    cm_hourAgo: "{n}h ago",
    cm_dayAgo: "{n}d ago",
    reg_registrant: "Submitted by",
    reg_courseUnset: "Course not set",
    reg_photoSection: "Photo Upload",
    reg_photoHint: "Place a 30mm ArUco marker next to the bead and capture together for accurate dimensional analysis",
    reg_change: "Change",
    reg_plateThickness: "Plate Thickness",
    reg_pipeOuterDiameter: "Pipe Outer Diameter",
    reg_pipeSpec: "Specs",
    reg_aiAnalyzingDefault: "AI analyzing...",
    reg_submitBtn: "Submit & AI Analyze",
    reg_pipeGuideTitle: "Pipe Outer Diameter Specs",
    reg_pipeHelp: "Tap a nominal size to auto-fill the outer diameter (mm).",
    reg_pipeFootnote: "* 250A and 300A have different outer diameters for carbon steel and stainless steel pipes.",
    reg_photoGuideTitle: "Photo Examples",
    stage_preparing: "📸 Preparing photos...",
    stage_uploading: "📤 Uploading to server...",
    stage_detecting: "🔍 Roboflow detecting defects...",
    stage_measuring: "📐 Calculating bead dimensions & straightness...",
    stage_aiAnalyzing: "🤖 {model} analyzing bead shape...",
    stage_writingReport: "📝 Writing comprehensive diagnostic report...",
    stage_finalizing: "✨ Finalizing results...",
    camera_webMsg: "Please use the camera on a mobile device.",
    camera_permNeeded: "Camera permission required",
    camera_permAllow: "Allow Permission",
    camera_arucoInstr: "Align the ArUco marker with the yellow guide\nin the top right and keep it level",
    login_appTitle: "AI Welding Education Platform",
    login_today: "Today",
    ai_analysisError: "An error occurred during AI analysis. Please try again.",
    photo_reuploadTitle: "Please re-upload the photo",
    analysis_errorTitle: "Analysis Error",
    conf_high: "The photo is clear and measurement references are well included, so the analysis is highly reliable.",
    conf_med: "Most items were clearly analyzed, but some measurements may include estimates.",
    conf_low: "Photo resolution, lighting, or shooting angle limits the accuracy of some items. Adding photos that include a ruler or photos taken from different angles will improve accuracy.",
    conf_verylow: "Accurate analysis was difficult due to photo quality or angle issues. Taking clearer photos along with side and back photos and a ruler will greatly improve reliability.",
    compare_accurate: "Accurate self-assessment",
    compare_under: "You are underestimating yourself",
    compare_over: "You are overestimating yourself",
  },
  vi: {
    save: "Lưu", cancel: "Hủy", confirm: "Xác nhận", error: "Lỗi",
    loading: "Đang tải", done: "Xong", required: "Bắt buộc", optional: "Tùy chọn",
    back: "Quay lại", close: "Đóng", select: "Chọn", language: "Ngôn ngữ",
    login_userId: "Tên đăng nhập", login_password: "Mật khẩu",
    login_btn: "Đăng nhập", login_register: "Đăng ký",
    login_noAccount: "Chưa có tài khoản?",
    login_errorEmpty: "Vui lòng nhập tên đăng nhập và mật khẩu.",
    login_errorInvalid: "Tên đăng nhập hoặc mật khẩu không đúng.",
    reg_title: "Đăng ký", reg_name: "Họ và tên", reg_role: "Vai trò",
    reg_courseName: "Tên khóa học", reg_courseNameRequired: "Học viên phải nhập tên khóa học.", reg_confirmPw: "Xác nhận mật khẩu",
    reg_profilePhoto: "Ảnh đại diện",
    reg_errorRequired: "Tên đăng nhập, mật khẩu và họ tên là bắt buộc.",
    reg_errorPwMatch: "Mật khẩu không khớp.",
    reg_errorPwLength: "Mật khẩu phải có ít nhất 4 ký tự.",
    reg_errorDuplicate: "Tên đăng nhập đã được sử dụng.",
    role_trainee: "Học viên", role_teacher: "Giáo viên", role_admin: "Quản trị viên",
    nav_gallery: "Thư viện", nav_diagnosis: "Xếp hạng", nav_coaching: "Huấn luyện AI",
    home_hello: "Xin chào",
    home_title: "Bạn muốn học gì?",
    home_subtitle: "Chọn chế độ học",
    home_theory: "Lý thuyết",
    home_theoryDesc: "Bài học hôm nay · OX",
    home_skill: "Nâng cao kỹ năng",
    home_skillDesc: "Chẩn đoán AI · Thư viện · Xếp hạng",
    theory_subtitle: "Chọn loại bài học",
    theory_today: "Bài học hôm nay",
    theory_today_desc: "3 câu mới mỗi ngày",
    theory_review: "Ôn tập",
    theory_ox: "Trò chơi OX",
    theory_ox_desc: "Đạt sóng cao nhất",
    theory_difficulty: "Độ khó",
    theory_next: "Tiếp",
    theory_submit: "Nộp bài",
    theory_finish: "Hoàn thành",
    theory_correct: "Đúng",
    theory_wrong: "Sai",
    theory_my_answer: "Câu của tôi",
    theory_correct_answer: "Đáp án đúng",
    theory_explanation: "Giải thích",
    theory_score_today: "Điểm hôm nay",
    theory_no_data: "Không có dữ liệu",
    theory_must_answer_all: "Vui lòng trả lời tất cả câu hỏi.",
    theory_submit_error: "Gửi bài thất bại.",
    theory_pdf_title: "Lịch sử lý thuyết PDF",
    ox_title: "Trò chơi OX",
    ox_hero: "Thử thách OX",
    ox_hero_desc: "Đạt sóng cao nhất với câu hỏi lý thuyết!",
    ox_ranking_title: "Bảng xếp hạng",
    ox_ranking_empty: "Chưa có bản ghi",
    ox_start: "Bắt đầu",
    ox_accuracy: "Độ chính xác",
    ox_resume: "Tiếp tục",
    ox_start_new: "Bắt đầu mới",
    ox_gameover_title: "SYSTEM FAILURE",
    ox_quit_title: "GAME ABORTED",
    ox_gameover_sub: "Căn cứ đã bị phá hủy",
    ox_final_wave: "Sóng cuối",
    ox_quiz_score: "Điểm quiz",
    ox_retry: "Chơi lại",
    ox_exit: "Thoát",
    gallery_empty: "Chưa có kết quả phân tích",
    gallery_upload: "Tải ảnh hàn lên để nhận\nchẩn đoán AI đầu tiên",
    gallery_new: "Phân tích mới",
    photo_title: "Đăng ký ảnh hàn",
    photo_front: "Ảnh mặt trước", photo_side: "Ảnh mặt bên", photo_back: "Ảnh mặt sau",
    photo_frontDesc: "Mặt trước (bắt buộc)",
    photo_sideDesc: "Đo chiều cao mối hàn (tùy chọn)",
    photo_backDesc: "Kiểm tra mặt sau (tùy chọn)",
    photo_addPhoto: "Thêm ảnh", photo_changePhoto: "Đổi ảnh",
    photo_camera: "Camera", photo_gallery: "Thư viện ảnh",
    photo_analyzeBtn: "Bắt đầu phân tích AI",
    photo_analyzing: "AI đang phân tích chất lượng hàn...",
    photo_weldProcess: "Quy trình hàn", photo_weldPosture: "Tư thế hàn",
    photo_weldMaterial: "Vật liệu", photo_selfScore: "Điểm tự đánh giá",
    photo_thickness: "Chiều dày vật liệu (mm)",
    photo_required: "Ảnh mặt trước là bắt buộc.",
    photo_scoreError: "Vui lòng nhập điểm từ 0 đến 100.",
    photo_selfScoreHint: "Điểm tự đánh giá (0~100)",
    diag_aiScore: "Điểm AI", diag_beadAnalysis: "Phân tích mối hàn",
    diag_defectEval: "Đánh giá khuyết tật", diag_aiReport: "Báo cáo toàn diện AI",
    diag_heatmap: "Phân tích trực quan (Heatmap)",
    diag_selfCompare: "So sánh tự đánh giá",
    diag_improvements: "Đề xuất cải thiện của AI",
    diag_trend: "Phân tích xu hướng tích lũy", diag_history: "Lịch sử kết quả đầy đủ",
    diag_pass: "ĐẠT", diag_fail: "TRƯỢT", diag_grade: "Xếp loại",
    diag_defectName: "Khuyết tật", diag_measured: "Đo được", diag_standard: "Tiêu chuẩn",
    diag_deduction: "Điểm trừ", diag_showMarkers: "Hiện vị trí khuyết tật",
    diag_hideMarkers: "Ẩn vị trí khuyết tật",
    diag_confidence: "Độ tin cậy AI", diag_avgScore: "Điểm trung bình",
    diag_bestScore: "Điểm cao nhất", diag_totalEvals: "Số lần đánh giá AI",
    diag_recentGrade: "Xếp loại gần nhất",
    diag_improvementMulti: "Hướng dẫn đào tạo cá nhân hóa dựa trên {n} lần đánh giá",
    diag_improvementSingle: "Hướng dẫn đào tạo dựa trên kết quả đánh giá lần này",
    diag_overallVerdict: "Phán quyết tổng thể", diag_top3: "Top 3 khuyết tật chính",
    diag_noDefect: "Không có khuyết tật - Chất lượng hàn xuất sắc!",
    bead_width: "Chiều rộng mối hàn", bead_height: "Chiều cao mối hàn",
    bead_filletSize: "Kích thước chân mối hàn góc", bead_straightness: "Độ thẳng", bead_pitch: "Độ đều bước hàn",
    label_process: "Quy trình hàn", label_posture: "Tư thế hàn", label_material: "Vật liệu",
    points_suffix: " điểm",
    rank_title: "Bảng Xếp Hạng AI", rank_subtitle: "Dựa trên điểm trung bình tích lũy",
    rank_total: "Tất cả", rank_weekly: "Tuần này", rank_daily: "Hôm nay",
    rank_myRank: "Hạng của tôi", rank_topRiser: "Tăng cao nhất", rank_topFaller: "Giảm nhiều nhất",
    rank_empty: "Chưa có kết quả", rank_noData: "Chưa có kết quả nào được đăng ký",
    rank_upload: "lần tải", rank_best: "Tốt nhất", rank_avg: "Trung bình",
    logout: "Đăng xuất",
    nav_members: "Thành viên",
    result_notFound: "Không tìm thấy kết quả",
    diag_outOf100: "/ 100 điểm",
    diag_aiSummary: "Phân tích Tổng hợp AI",
    diag_historyReflected: "(phản ánh {n} lần đánh giá trước)",
    diag_sideAnalyzing: "Đang phân tích ảnh bên hoặc chưa tải lên",
    diag_backAnalyzing: "Đang phân tích ảnh sau hoặc chưa tải lên",
    diag_sideNoData: "Không có dữ liệu phân tích ảnh bên",
    diag_backNoData: "Không có dữ liệu phân tích ảnh sau",
    diag_coordsLoading: "Đang chuẩn bị dữ liệu tọa độ",
    diag_noDefectAi: "AI không phát hiện khuyết tật",
    diag_zoomHint: "Bóp: phóng to · Kéo khi đã phóng · Nhấn đúp: đặt lại",
    diag_noPhoto: "Không có ảnh",
    diag_beadStackTitle: "Chế độ xếp lớp mối hàn",
    diag_beadStackMsg: "Xếp lớp mối hàn không đánh giá khuyết tật.",
    diag_deviation: "lệch",
    diag_straightnessLabel: "Độ thẳng",
    diag_widthLabel: "Chiều rộng",
    diag_beadType: "Loại mối hàn",
    diag_selfScore: "Điểm tự đánh giá",
    diag_atLeast2: "Biểu đồ xu hướng sẽ hiển thị sau 2 lần đánh giá trở lên",
    trend_totalAvg: "Trung bình {n} lần",
    trend_skill: "Xu hướng kỹ năng",
    trend_improved: "▲ Tiến bộ (+{n} điểm)",
    trend_declined: "▼ Giảm ({n} điểm)",
    trend_vsPrev: "so với trước",
    trend_currentResult: "Kết quả hiện tại",
    adm_deleteTitle: "Xóa kết quả",
    adm_deleteConfirm: "Xóa kết quả của {name}?",
    adm_delete: "Xóa",
    adm_savedTitle: "Đã lưu",
    adm_savedMsg: "Phản hồi đã được lưu.\nAI sẽ áp dụng tiêu chuẩn này từ lần phân tích tiếp theo.",
    adm_saveFailed: "Lưu phản hồi thất bại.",
    adm_networkErr: "Đã xảy ra lỗi mạng.",
    adm_feedbackTitle: "Phản hồi phân tích AI",
    adm_feedbackDesc: "Hãy mô tả những gì AI phân tích sai.\nPhản hồi đã lưu sẽ được áp dụng cho tất cả các phân tích sau.",
    adm_target: "Đối tượng",
    adm_feedbackPlaceholder: "Ví dụ: Khu vực được đánh dấu là spatter thực ra là overlap.",
    adm_saveSubmit: "Lưu & Áp dụng vào AI",
    cm_comments: "Bình luận",
    cm_empty: "Chưa có bình luận. Hãy là người đầu tiên!",
    cm_reply: "Trả lời",
    cm_replyTo: "Trả lời {name}",
    cm_inputPlaceholder: "Viết bình luận...",
    cm_replyInputPlaceholder: "Trả lời {name}...",
    cm_deleteTitle: "Xóa bình luận",
    cm_deleteConfirm: "Xóa bình luận này?",
    cm_addFailed: "Đăng bình luận thất bại.",
    cm_deleteFailed: "Xóa bình luận thất bại.",
    cm_justNow: "vừa xong",
    cm_minAgo: "{n} phút trước",
    cm_hourAgo: "{n} giờ trước",
    cm_dayAgo: "{n} ngày trước",
    reg_registrant: "Người đăng ký",
    reg_courseUnset: "Chưa có khóa học",
    reg_photoSection: "Tải ảnh",
    reg_photoHint: "Đặt mã ArUco 30mm bên cạnh mối hàn khi chụp để phân tích kích thước chính xác",
    reg_change: "Đổi",
    reg_plateThickness: "Độ dày tấm",
    reg_pipeOuterDiameter: "Đường kính ngoài ống",
    reg_pipeSpec: "Bảng quy cách",
    reg_aiAnalyzingDefault: "AI đang phân tích...",
    reg_submitBtn: "Đăng ký & Phân tích AI",
    reg_pipeGuideTitle: "Bảng đường kính ngoài ống",
    reg_pipeHelp: "Nhấn vào kích cỡ danh nghĩa để tự động điền đường kính ngoài (mm).",
    reg_pipeFootnote: "* 250A và 300A có đường kính ngoài khác nhau giữa ống thép thường và ống thép không gỉ.",
    reg_photoGuideTitle: "Ảnh ví dụ",
    stage_preparing: "📸 Đang chuẩn bị ảnh...",
    stage_uploading: "📤 Đang tải ảnh lên máy chủ...",
    stage_detecting: "🔍 Roboflow đang phát hiện khuyết tật...",
    stage_measuring: "📐 Đang tính kích thước & độ thẳng...",
    stage_aiAnalyzing: "🤖 {model} đang phân tích hình dạng mối hàn...",
    stage_writingReport: "📝 Đang viết báo cáo chẩn đoán tổng hợp...",
    stage_finalizing: "✨ Đang hoàn tất kết quả...",
    camera_webMsg: "Vui lòng sử dụng camera trên thiết bị di động.",
    camera_permNeeded: "Cần quyền truy cập camera",
    camera_permAllow: "Cho phép",
    camera_arucoInstr: "Căn chỉnh mã ArUco với khung dẫn vàng\nở góc trên bên phải và giữ ngang",
    login_appTitle: "Nền tảng Giáo dục Hàn AI",
    login_today: "Hôm nay",
    ai_analysisError: "Đã xảy ra lỗi trong quá trình phân tích AI. Vui lòng thử lại.",
    photo_reuploadTitle: "Vui lòng tải lại ảnh",
    analysis_errorTitle: "Lỗi phân tích",
    conf_high: "Ảnh rõ nét và có đầy đủ chuẩn đo lường nên phân tích với độ tin cậy cao.",
    conf_med: "Hầu hết các mục được phân tích rõ ràng, nhưng một số giá trị đo có thể bao gồm ước tính.",
    conf_low: "Độ phân giải ảnh, ánh sáng hoặc góc chụp làm hạn chế độ chính xác của một số mục. Thêm ảnh có thước đo hoặc ảnh từ nhiều góc khác nhau sẽ cải thiện độ chính xác.",
    conf_verylow: "Khó phân tích chính xác do chất lượng ảnh hoặc góc chụp. Chụp ảnh rõ hơn cùng với ảnh mặt bên, mặt sau và thước đo sẽ cải thiện đáng kể độ tin cậy.",
    compare_accurate: "Tự đánh giá chính xác",
    compare_under: "Bạn đang đánh giá thấp bản thân",
    compare_over: "Bạn đang đánh giá quá cao bản thân",
  },
  th: {
    save: "บันทึก", cancel: "ยกเลิก", confirm: "ยืนยัน", error: "ข้อผิดพลาด",
    loading: "กำลังโหลด", done: "เสร็จสิ้น", required: "จำเป็น", optional: "ตัวเลือก",
    back: "กลับ", close: "ปิด", select: "เลือก", language: "ภาษา",
    login_userId: "ชื่อผู้ใช้", login_password: "รหัสผ่าน",
    login_btn: "เข้าสู่ระบบ", login_register: "สมัครสมาชิก",
    login_noAccount: "ยังไม่มีบัญชี?",
    login_errorEmpty: "กรุณาใส่ชื่อผู้ใช้และรหัสผ่าน",
    login_errorInvalid: "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง",
    reg_title: "สมัครสมาชิก", reg_name: "ชื่อ-นามสกุล", reg_role: "บทบาท",
    reg_courseName: "ชื่อหลักสูตร", reg_courseNameRequired: "ผู้ฝึกอบรมต้องระบุชื่อหลักสูตร", reg_confirmPw: "ยืนยันรหัสผ่าน",
    reg_profilePhoto: "รูปโปรไฟล์",
    reg_errorRequired: "ชื่อผู้ใช้ รหัสผ่าน และชื่อ เป็นข้อมูลที่จำเป็น",
    reg_errorPwMatch: "รหัสผ่านไม่ตรงกัน",
    reg_errorPwLength: "รหัสผ่านต้องมีอย่างน้อย 4 ตัวอักษร",
    reg_errorDuplicate: "ชื่อผู้ใช้นี้ถูกใช้งานแล้ว",
    role_trainee: "ผู้เรียน", role_teacher: "ผู้สอน", role_admin: "ผู้ดูแลระบบ",
    nav_gallery: "แกลเลอรี", nav_diagnosis: "การจัดอันดับ", nav_coaching: "โค้ช AI สด",
    home_hello: "สวัสดี",
    home_title: "อยากเรียนอะไรวันนี้?",
    home_subtitle: "เลือกโหมดการเรียน",
    home_theory: "ทฤษฎี",
    home_theoryDesc: "บทเรียนวันนี้ · OX",
    home_skill: "พัฒนาทักษะ",
    home_skillDesc: "AI · แกลเลอรี · จัดอันดับ",
    theory_subtitle: "เลือกประเภทการเรียน",
    theory_today: "บทเรียนวันนี้",
    theory_today_desc: "3 ข้อใหม่ทุกวัน",
    theory_review: "ทบทวน",
    theory_ox: "เกมส์ OX",
    theory_ox_desc: "พิชิต Wave สูงสุด",
    theory_difficulty: "ความยาก",
    theory_next: "ถัดไป",
    theory_submit: "ส่ง",
    theory_finish: "เสร็จสิ้น",
    theory_correct: "ถูก",
    theory_wrong: "ผิด",
    theory_my_answer: "คำตอบของฉัน",
    theory_correct_answer: "เฉลย",
    theory_explanation: "คำอธิบาย",
    theory_score_today: "คะแนนวันนี้",
    theory_no_data: "ไม่มีข้อมูล",
    theory_must_answer_all: "กรุณาตอบทุกข้อ",
    theory_submit_error: "ส่งคำตอบล้มเหลว",
    theory_pdf_title: "ประวัติทฤษฎี PDF",
    ox_title: "เกมส์ OX",
    ox_hero: "OX Challenge",
    ox_hero_desc: "พิชิต Wave สูงสุดด้วยทฤษฎี!",
    ox_ranking_title: "อันดับสูงสุด",
    ox_ranking_empty: "ยังไม่มีข้อมูล",
    ox_start: "เริ่มเกม",
    ox_accuracy: "ความแม่นยำ",
    ox_resume: "เล่นต่อ",
    ox_start_new: "เริ่มใหม่",
    ox_gameover_title: "SYSTEM FAILURE",
    ox_quit_title: "GAME ABORTED",
    ox_gameover_sub: "ฐานถูกทำลาย",
    ox_final_wave: "เวฟสุดท้าย",
    ox_quiz_score: "คะแนนควิซ",
    ox_retry: "เล่นอีกครั้ง",
    ox_exit: "ออก",
    gallery_empty: "ยังไม่มีผลการวิเคราะห์",
    gallery_upload: "อัปโหลดรูปงานเชื่อมเพื่อรับ\nการวินิจฉัย AI ครั้งแรก",
    gallery_new: "วิเคราะห์ใหม่",
    photo_title: "ลงทะเบียนรูปงานเชื่อม",
    photo_front: "รูปด้านหน้า", photo_side: "รูปด้านข้าง", photo_back: "รูปด้านหลัง",
    photo_frontDesc: "ด้านหน้า (จำเป็น)",
    photo_sideDesc: "วัดความสูงลูกปัด (ตัวเลือก)",
    photo_backDesc: "ตรวจสอบด้านหลัง (ตัวเลือก)",
    photo_addPhoto: "เพิ่มรูป", photo_changePhoto: "เปลี่ยนรูป",
    photo_camera: "กล้อง", photo_gallery: "แกลเลอรี",
    photo_analyzeBtn: "เริ่มวิเคราะห์ AI",
    photo_analyzing: "AI กำลังวิเคราะห์คุณภาพงานเชื่อม...",
    photo_weldProcess: "กระบวนการเชื่อม", photo_weldPosture: "ท่าทางการเชื่อม",
    photo_weldMaterial: "วัสดุ", photo_selfScore: "คะแนนประเมินตนเอง",
    photo_thickness: "ความหนาวัสดุ (มม.)",
    photo_required: "ต้องใช้รูปด้านหน้า",
    photo_scoreError: "กรุณาใส่คะแนนระหว่าง 0 ถึง 100",
    photo_selfScoreHint: "คะแนนประเมินตนเอง (0~100)",
    diag_aiScore: "คะแนน AI", diag_beadAnalysis: "วิเคราะห์ลูกปัด",
    diag_defectEval: "ประเมินข้อบกพร่อง", diag_aiReport: "รายงาน AI ฉบับสมบูรณ์",
    diag_heatmap: "การวิเคราะห์ภาพ (Heatmap)",
    diag_selfCompare: "เปรียบเทียบการประเมินตนเอง",
    diag_improvements: "ข้อเสนอแนะการปรับปรุงจาก AI",
    diag_trend: "วิเคราะห์แนวโน้มสะสม", diag_history: "ประวัติผลลัพธ์ทั้งหมด",
    diag_pass: "ผ่าน", diag_fail: "ไม่ผ่าน", diag_grade: "เกรด",
    diag_defectName: "ข้อบกพร่อง", diag_measured: "ค่าที่วัดได้", diag_standard: "มาตรฐาน",
    diag_deduction: "หักคะแนน", diag_showMarkers: "แสดงตำแหน่งบกพร่อง",
    diag_hideMarkers: "ซ่อนตำแหน่งบกพร่อง",
    diag_confidence: "ความมั่นใจ AI", diag_avgScore: "คะแนนเฉลี่ย",
    diag_bestScore: "คะแนนสูงสุด", diag_totalEvals: "การประเมิน AI",
    diag_recentGrade: "เกรดล่าสุด",
    diag_improvementMulti: "คู่มือฝึกอบรมเฉพาะบุคคลจากผลการประเมิน {n} ครั้ง",
    diag_improvementSingle: "คู่มือฝึกอบรมตามผลการประเมินครั้งนี้",
    diag_overallVerdict: "ผลการตัดสินรวม", diag_top3: "3 ข้อบกพร่องหลัก",
    diag_noDefect: "ไม่พบข้อบกพร่อง - คุณภาพการเชื่อมยอดเยี่ยม!",
    bead_width: "ความกว้างลูกปัด", bead_height: "ความสูงลูกปัด",
    bead_filletSize: "ขาเชื่อม", bead_straightness: "ความตรง", bead_pitch: "ความสม่ำเสมอระยะ",
    label_process: "กระบวนการเชื่อม", label_posture: "ท่าทางเชื่อม", label_material: "วัสดุ",
    points_suffix: " คะแนน",
    rank_title: "อันดับ AI", rank_subtitle: "เรียงตามคะแนนเฉลี่ยสะสม",
    rank_total: "ทั้งหมด", rank_weekly: "สัปดาห์นี้", rank_daily: "วันนี้",
    rank_myRank: "อันดับของฉัน", rank_topRiser: "ขึ้นสูงสุด", rank_topFaller: "ลดมากสุด",
    rank_empty: "ไม่มีผลลัพธ์", rank_noData: "ยังไม่มีผลลัพธ์ที่ลงทะเบียน",
    rank_upload: "อัปโหลด", rank_best: "สูงสุด", rank_avg: "เฉลี่ย",
    logout: "ออกจากระบบ",
    nav_members: "สมาชิก",
    result_notFound: "ไม่พบผลลัพธ์",
    diag_outOf100: "/ 100 คะแนน",
    diag_aiSummary: "การวิเคราะห์ครอบคลุมโดย AI",
    diag_historyReflected: "(สะท้อนประวัติ {n} ครั้ง)",
    diag_sideAnalyzing: "กำลังวิเคราะห์ภาพด้านข้างหรือยังไม่ได้อัปโหลด",
    diag_backAnalyzing: "กำลังวิเคราะห์ภาพด้านหลังหรือยังไม่ได้อัปโหลด",
    diag_sideNoData: "ไม่มีข้อมูลวิเคราะห์ภาพด้านข้าง",
    diag_backNoData: "ไม่มีข้อมูลวิเคราะห์ภาพด้านหลัง",
    diag_coordsLoading: "กำลังเตรียมข้อมูลพิกัด",
    diag_noDefectAi: "AI ไม่พบข้อบกพร่อง",
    diag_zoomHint: "บีบ: ซูม · ลากเมื่อซูม · แตะสองครั้ง: รีเซ็ต",
    diag_noPhoto: "ไม่มีภาพ",
    diag_beadStackTitle: "โหมดซ้อนลูกปัด",
    diag_beadStackMsg: "การซ้อนลูกปัดไม่ประเมินข้อบกพร่อง",
    diag_deviation: "เบี่ยงเบน",
    diag_straightnessLabel: "ความตรง",
    diag_widthLabel: "ความกว้าง",
    diag_beadType: "ประเภทลูกปัด",
    diag_selfScore: "คะแนนตนเอง",
    diag_atLeast2: "กราฟแนวโน้มจะแสดงหลังจากประเมินตั้งแต่ 2 ครั้งขึ้นไป",
    trend_totalAvg: "เฉลี่ย {n} ครั้ง",
    trend_skill: "แนวโน้มทักษะ",
    trend_improved: "▲ ดีขึ้น (+{n} คะแนน)",
    trend_declined: "▼ ลดลง ({n} คะแนน)",
    trend_vsPrev: "เทียบกับก่อนหน้า",
    trend_currentResult: "ผลปัจจุบัน",
    adm_deleteTitle: "ลบผลลัพธ์",
    adm_deleteConfirm: "ลบผลลัพธ์ของ {name} หรือไม่?",
    adm_delete: "ลบ",
    adm_savedTitle: "บันทึกแล้ว",
    adm_savedMsg: "บันทึกข้อเสนอแนะแล้ว\nAI จะใช้มาตรฐานนี้ตั้งแต่การวิเคราะห์ครั้งถัดไป",
    adm_saveFailed: "บันทึกข้อเสนอแนะไม่สำเร็จ",
    adm_networkErr: "เกิดข้อผิดพลาดเครือข่าย",
    adm_feedbackTitle: "ข้อเสนอแนะการวิเคราะห์ AI",
    adm_feedbackDesc: "อธิบายสิ่งที่ AI วิเคราะห์ผิด\nข้อเสนอแนะที่บันทึกจะใช้กับการวิเคราะห์ทั้งหมดในอนาคต",
    adm_target: "เป้าหมาย",
    adm_feedbackPlaceholder: "ตัวอย่าง: บริเวณที่ระบุว่าเป็น spatter จริงๆ คือ overlap",
    adm_saveSubmit: "บันทึก & ใช้กับ AI",
    cm_comments: "ความคิดเห็น",
    cm_empty: "ยังไม่มีความคิดเห็น มาเป็นคนแรก!",
    cm_reply: "ตอบกลับ",
    cm_replyTo: "ตอบกลับ {name}",
    cm_inputPlaceholder: "เขียนความคิดเห็น...",
    cm_replyInputPlaceholder: "ตอบกลับ {name}...",
    cm_deleteTitle: "ลบความคิดเห็น",
    cm_deleteConfirm: "ลบความคิดเห็นนี้?",
    cm_addFailed: "โพสต์ความคิดเห็นไม่สำเร็จ",
    cm_deleteFailed: "ลบความคิดเห็นไม่สำเร็จ",
    cm_justNow: "เมื่อสักครู่",
    cm_minAgo: "{n} นาทีที่แล้ว",
    cm_hourAgo: "{n} ชั่วโมงที่แล้ว",
    cm_dayAgo: "{n} วันที่แล้ว",
    reg_registrant: "ผู้ลงทะเบียน",
    reg_courseUnset: "ยังไม่ระบุหลักสูตร",
    reg_photoSection: "อัปโหลดรูป",
    reg_photoHint: "วาง ArUco marker ขนาด 30 มม. ข้างลูกปัดเพื่อการวิเคราะห์ขนาดที่แม่นยำ",
    reg_change: "เปลี่ยน",
    reg_plateThickness: "ความหนาแผ่น",
    reg_pipeOuterDiameter: "เส้นผ่านศูนย์กลางท่อภายนอก",
    reg_pipeSpec: "ตารางสเปก",
    reg_aiAnalyzingDefault: "AI กำลังวิเคราะห์...",
    reg_submitBtn: "ส่ง & วิเคราะห์ AI",
    reg_pipeGuideTitle: "ตารางเส้นผ่านศูนย์กลางท่อภายนอก",
    reg_pipeHelp: "แตะที่ขนาดระบุเพื่อกรอกเส้นผ่านศูนย์กลางอัตโนมัติ (มม.)",
    reg_pipeFootnote: "* 250A และ 300A มีขนาดต่างกันระหว่างท่อเหล็กทั่วไปกับท่อสแตนเลส",
    reg_photoGuideTitle: "ภาพตัวอย่าง",
    stage_preparing: "📸 กำลังเตรียมรูป...",
    stage_uploading: "📤 กำลังอัปโหลด...",
    stage_detecting: "🔍 Roboflow กำลังตรวจหาข้อบกพร่อง...",
    stage_measuring: "📐 กำลังคำนวณขนาด & ความตรง...",
    stage_aiAnalyzing: "🤖 {model} กำลังวิเคราะห์รูปร่างลูกปัด...",
    stage_writingReport: "📝 กำลังเขียนรายงานการวินิจฉัยฉบับสมบูรณ์...",
    stage_finalizing: "✨ กำลังจัดการผลลัพธ์...",
    camera_webMsg: "กรุณาใช้กล้องบนอุปกรณ์มือถือ",
    camera_permNeeded: "ต้องการสิทธิ์เข้าถึงกล้อง",
    camera_permAllow: "อนุญาต",
    camera_arucoInstr: "จัด ArUco marker ให้ตรงกับเส้นนำสีเหลือง\nที่มุมขวาบนและถือให้อยู่ในแนวนอน",
    login_appTitle: "แพลตฟอร์มการศึกษาการเชื่อมด้วย AI",
    login_today: "วันนี้",
    ai_analysisError: "เกิดข้อผิดพลาดระหว่างการวิเคราะห์ AI กรุณาลองใหม่",
    photo_reuploadTitle: "กรุณาอัปโหลดรูปใหม่",
    analysis_errorTitle: "ข้อผิดพลาดการวิเคราะห์",
    conf_high: "ภาพคมชัดและรวมเกณฑ์การวัดไว้อย่างครบถ้วน จึงวิเคราะห์ด้วยความน่าเชื่อถือสูง",
    conf_med: "รายการส่วนใหญ่ได้รับการวิเคราะห์อย่างชัดเจน แต่ค่าการวัดบางค่าอาจรวมการประมาณ",
    conf_low: "ความละเอียดของภาพ แสง หรือมุมถ่ายภาพจำกัดความแม่นยำของบางรายการ การเพิ่มภาพที่มีไม้บรรทัดหรือภาพจากมุมต่างๆ จะช่วยเพิ่มความแม่นยำ",
    conf_verylow: "วิเคราะห์อย่างแม่นยำได้ยากเนื่องจากปัญหาคุณภาพภาพหรือมุมถ่าย การถ่ายภาพที่คมชัดขึ้นพร้อมภาพด้านข้าง ด้านหลัง และไม้บรรทัดจะเพิ่มความน่าเชื่อถืออย่างมาก",
    compare_accurate: "การประเมินตนเองที่แม่นยำ",
    compare_under: "คุณกำลังประเมินตนเองต่ำเกินไป",
    compare_over: "คุณกำลังประเมินตนเองสูงเกินไป",
  },
  fil: {
    save: "I-save", cancel: "Kanselahin", confirm: "Kumpirmahin", error: "Error",
    loading: "Naglo-load", done: "Tapos na", required: "Kailangan", optional: "Opsyonal",
    back: "Bumalik", close: "Isara", select: "Pumili", language: "Wika",
    login_userId: "Username", login_password: "Password",
    login_btn: "Mag-login", login_register: "Mag-rehistro",
    login_noAccount: "Wala pang account?",
    login_errorEmpty: "Mangyaring ilagay ang username at password.",
    login_errorInvalid: "Mali ang username o password.",
    reg_title: "Mag-rehistro", reg_name: "Pangalan", reg_role: "Papel",
    reg_courseName: "Pangalan ng Kurso", reg_courseNameRequired: "Ang mga traineee ay dapat maglagay ng pangalan ng kurso.", reg_confirmPw: "Kumpirmahin ang Password",
    reg_profilePhoto: "Larawan ng Profile",
    reg_errorRequired: "Ang username, password, at pangalan ay kailangan.",
    reg_errorPwMatch: "Hindi magkapareho ang password.",
    reg_errorPwLength: "Ang password ay dapat na hindi bababa sa 4 na character.",
    reg_errorDuplicate: "Ginagamit na ang username.",
    role_trainee: "Mag-aaral", role_teacher: "Guro", role_admin: "Admin",
    nav_gallery: "Galerya", nav_diagnosis: "Ranggo", nav_coaching: "AI Coaching",
    home_hello: "Kumusta",
    home_title: "Ano ang gusto mong pag-aralan?",
    home_subtitle: "Pumili ng learning mode",
    home_theory: "Teorya",
    home_theoryDesc: "Aralin ngayon · OX",
    home_skill: "Skill Up",
    home_skillDesc: "AI · Galerya · Ranggo",
    theory_subtitle: "Pumili ng uri ng aralin",
    theory_today: "Aralin Ngayon",
    theory_today_desc: "3 bagong tanong araw-araw",
    theory_review: "Balik-aral",
    theory_ox: "OX Quiz Game",
    theory_ox_desc: "Abutin ang pinakamataas na wave",
    theory_difficulty: "Antas",
    theory_next: "Susunod",
    theory_submit: "Isumite",
    theory_finish: "Tapos",
    theory_correct: "Tama",
    theory_wrong: "Mali",
    theory_my_answer: "Sagot ko",
    theory_correct_answer: "Tamang sagot",
    theory_explanation: "Paliwanag",
    theory_score_today: "Iskor ngayon",
    theory_no_data: "Walang datos",
    theory_must_answer_all: "Sagutin lahat ng tanong.",
    theory_submit_error: "Nabigo ang pagsumite.",
    theory_pdf_title: "Theory History PDF",
    ox_title: "OX Quiz Game",
    ox_hero: "OX Challenge",
    ox_hero_desc: "Subukan abutin ang pinakamataas na wave!",
    ox_ranking_title: "Top Wave Ranking",
    ox_ranking_empty: "Wala pang record",
    ox_start: "Simulan",
    ox_accuracy: "Katumpakan",
    ox_resume: "Magpatuloy",
    ox_start_new: "Magsimula Ulit",
    ox_gameover_title: "SYSTEM FAILURE",
    ox_quit_title: "GAME ABORTED",
    ox_gameover_sub: "Nawasak ang base",
    ox_final_wave: "Huling Wave",
    ox_quiz_score: "Iskor sa Quiz",
    ox_retry: "Subukan Ulit",
    ox_exit: "Lumabas",
    gallery_empty: "Wala pang mga resulta ng pagsusuri",
    gallery_upload: "Mag-upload ng larawan ng welding\npara sa unang AI diagnosis",
    gallery_new: "Bagong Pagsusuri",
    photo_title: "Irehistro ang Welding Photo",
    photo_front: "Harap na Larawan", photo_side: "Gilid na Larawan", photo_back: "Likod na Larawan",
    photo_frontDesc: "Harap ng cap pass (kailangan)",
    photo_sideDesc: "Para sa pagsukat ng taas ng bead (opsyonal)",
    photo_backDesc: "Para sa inspeksyon ng root pass (opsyonal)",
    photo_addPhoto: "Magdagdag ng Larawan", photo_changePhoto: "Palitan ang Larawan",
    photo_camera: "Camera", photo_gallery: "Galerya",
    photo_analyzeBtn: "Simulan ang AI Analysis",
    photo_analyzing: "Sinusuri ng AI ang kalidad ng welding...",
    photo_weldProcess: "Proseso ng Welding", photo_weldPosture: "Posisyon ng Welding",
    photo_weldMaterial: "Materyales", photo_selfScore: "Sariling Puntos",
    photo_thickness: "Kapal ng Materyales (mm)",
    photo_required: "Kailangan ang harap na larawan.",
    photo_scoreError: "Mangyaring maglagay ng puntos mula 0 hanggang 100.",
    photo_selfScoreHint: "Sariling Puntos (0~100)",
    diag_aiScore: "AI Score", diag_beadAnalysis: "Bead Analysis",
    diag_defectEval: "Defect Evaluation", diag_aiReport: "AI Comprehensive Report",
    diag_heatmap: "Visual Analysis (Heatmap)",
    diag_selfCompare: "Self Assessment Comparison",
    diag_improvements: "AI Improvement Suggestions",
    diag_trend: "Cumulative Trend Analysis", diag_history: "Full Result History",
    diag_pass: "PUMASA", diag_fail: "BUMAGSAK", diag_grade: "Grado",
    diag_defectName: "Depekto", diag_measured: "Nasukat", diag_standard: "Pamantayan",
    diag_deduction: "Pagbabawas", diag_showMarkers: "Ipakita ang mga Defect Marker",
    diag_hideMarkers: "Itago ang mga Defect Marker",
    diag_confidence: "AI Confidence", diag_avgScore: "Average Score",
    diag_bestScore: "Pinakamataas na Score", diag_totalEvals: "AI Evaluations",
    diag_recentGrade: "Pinakabagong Grado",
    diag_improvementMulti: "Personalized na gabay sa pagsasanay batay sa {n} pagsusuri",
    diag_improvementSingle: "Gabay sa pagsasanay batay sa pagsusuring ito",
    diag_overallVerdict: "Pangkalahatang Hatol", diag_top3: "Top 3 Depekto",
    diag_noDefect: "Walang depekto - Mahusay na kalidad ng welding!",
    bead_width: "Lapad ng Bead", bead_height: "Taas ng Bead",
    bead_filletSize: "Sukat ng Fillet", bead_straightness: "Katuwiran", bead_pitch: "Pagkakapantay ng Pitch",
    label_process: "Proseso ng Welding", label_posture: "Posisyon ng Welding", label_material: "Materyales",
    points_suffix: " pts",
    rank_title: "AI Ranking", rank_subtitle: "Batay sa average score",
    rank_total: "Lahat", rank_weekly: "Lingguhan", rank_daily: "Ngayon",
    rank_myRank: "Aking Ranggo", rank_topRiser: "Pinakamataas na Umakyat", rank_topFaller: "Pinakamataas na Bumaba",
    rank_empty: "Walang Resulta", rank_noData: "Wala pang nairehistrong resulta",
    rank_upload: "upload", rank_best: "Pinakamataas", rank_avg: "Average",
    logout: "Mag-logout",
    nav_members: "Mga Miyembro",
    result_notFound: "Walang nahanap na resulta",
    diag_outOf100: "/ 100 puntos",
    diag_aiSummary: "Komprehensibong Pagsusuri ng AI",
    diag_historyReflected: "(salamin sa {n} sesyon ng kasaysayan)",
    diag_sideAnalyzing: "Sinusuri ang side photo o hindi pa na-upload",
    diag_backAnalyzing: "Sinusuri ang back photo o hindi pa na-upload",
    diag_sideNoData: "Walang data ng pagsusuri sa side photo",
    diag_backNoData: "Walang data ng pagsusuri sa back photo",
    diag_coordsLoading: "Inihahanda ang coordinate data",
    diag_noDefectAi: "Walang depektong nakita ng AI",
    diag_zoomHint: "Pinch: zoom · Drag kapag naka-zoom · Double tap: i-reset",
    diag_noPhoto: "Walang larawan",
    diag_beadStackTitle: "Bead Stacking Mode",
    diag_beadStackMsg: "Hindi sinusuri ng bead stacking ang mga depekto.",
    diag_deviation: "deviation",
    diag_straightnessLabel: "Katuwiran",
    diag_widthLabel: "Lapad",
    diag_beadType: "Uri ng Bead",
    diag_selfScore: "Sariling Puntos",
    diag_atLeast2: "Lalabas ang trend graph pagkatapos ng 2 o higit pang ebalwasyon",
    trend_totalAvg: "Average ng {n} sesyon",
    trend_skill: "Trend ng Kakayahan",
    trend_improved: "▲ Bumuti (+{n} pts)",
    trend_declined: "▼ Bumaba ({n} pts)",
    trend_vsPrev: "kumpara sa nakaraan",
    trend_currentResult: "Kasalukuyang resulta",
    adm_deleteTitle: "Burahin ang Resulta",
    adm_deleteConfirm: "Burahin ang resulta ni {name}?",
    adm_delete: "Burahin",
    adm_savedTitle: "Na-save",
    adm_savedMsg: "Na-save ang feedback.\nGagamitin ito ng AI sa susunod na pagsusuri.",
    adm_saveFailed: "Hindi na-save ang feedback.",
    adm_networkErr: "Nagkaroon ng network error.",
    adm_feedbackTitle: "Feedback sa Pagsusuri ng AI",
    adm_feedbackDesc: "Ilarawan ang nagkamali ang AI.\nGagamitin ang feedback sa lahat ng susunod na pagsusuri.",
    adm_target: "Target",
    adm_feedbackPlaceholder: "Halimbawa: Ang minarkahan na spatter ay overlap talaga.",
    adm_saveSubmit: "I-save & Ipatupad sa AI",
    cm_comments: "Mga Komento",
    cm_empty: "Wala pang komento. Maging unang magkomento!",
    cm_reply: "Tumugon",
    cm_replyTo: "Tumugon kay {name}",
    cm_inputPlaceholder: "Sumulat ng komento...",
    cm_replyInputPlaceholder: "Tumugon kay {name}...",
    cm_deleteTitle: "Burahin ang Komento",
    cm_deleteConfirm: "Burahin ang komentong ito?",
    cm_addFailed: "Hindi na-post ang komento.",
    cm_deleteFailed: "Hindi nabura ang komento.",
    cm_justNow: "kanina lang",
    cm_minAgo: "{n}m ang nakaraan",
    cm_hourAgo: "{n}h ang nakaraan",
    cm_dayAgo: "{n}d ang nakaraan",
    reg_registrant: "Nagsumite",
    reg_courseUnset: "Walang kursong itinakda",
    reg_photoSection: "Pag-upload ng Larawan",
    reg_photoHint: "Maglagay ng 30mm ArUco marker sa tabi ng bead at i-capture nang sabay para sa tumpak na pagsusuri ng dimensyon",
    reg_change: "Palitan",
    reg_plateThickness: "Kapal ng Plato",
    reg_pipeOuterDiameter: "Outer Diameter ng Tubo",
    reg_pipeSpec: "Spec Table",
    reg_aiAnalyzingDefault: "Sinusuri ng AI...",
    reg_submitBtn: "Isumite & Suriin ng AI",
    reg_pipeGuideTitle: "Spec ng Outer Diameter ng Tubo",
    reg_pipeHelp: "Pindutin ang nominal size para auto-fill ang outer diameter (mm).",
    reg_pipeFootnote: "* Magkaiba ang outer diameter ng 250A at 300A para sa carbon steel at stainless steel pipes.",
    reg_photoGuideTitle: "Photo Examples",
    stage_preparing: "📸 Inihahanda ang mga larawan...",
    stage_uploading: "📤 Ina-upload sa server...",
    stage_detecting: "🔍 Naghahanap ng depekto ang Roboflow...",
    stage_measuring: "📐 Kinukuwenta ang dimensyon at straightness...",
    stage_aiAnalyzing: "🤖 Sinusuri ng {model} ang hugis ng bead...",
    stage_writingReport: "📝 Sinusulat ang komprehensibong ulat...",
    stage_finalizing: "✨ Tinatapos ang resulta...",
    camera_webMsg: "Mangyaring gamitin ang camera sa mobile device.",
    camera_permNeeded: "Kailangan ng permiso sa camera",
    camera_permAllow: "Payagan",
    camera_arucoInstr: "I-align ang ArUco marker sa dilaw na guide\nsa kanang itaas at panatilihing pantay",
    login_appTitle: "AI Welding Education Platform",
    login_today: "Ngayon",
    ai_analysisError: "May error sa AI analysis. Pakisubukang muli.",
    photo_reuploadTitle: "Mangyaring i-upload muli ang larawan",
    analysis_errorTitle: "Error sa Pagsusuri",
    conf_high: "Malinaw ang larawan at maayos na nakapaloob ang mga sukatan kaya ang pagsusuri ay may mataas na kasiguraduhan.",
    conf_med: "Karamihan sa mga aytem ay nasuri nang malinaw, ngunit ang ilang sukat ay maaaring may kasamang pagtataya.",
    conf_low: "Ang resolusyon ng larawan, ilaw, o anggulo ng pagkuha ay naglilimita sa katumpakan ng ilang aytem. Ang pagdagdag ng mga larawan na may ruler o mga larawan mula sa iba't ibang anggulo ay magpapabuti ng katumpakan.",
    conf_verylow: "Mahirap magkaroon ng tumpak na pagsusuri dahil sa kalidad ng larawan o anggulo. Ang mas malinaw na mga larawan kasama ang mga gilid, likod, at ruler ay lubos na magpapabuti sa kasiguraduhan.",
    compare_accurate: "Tumpak na sariling pagtatasa",
    compare_under: "Minamaliit mo ang iyong sarili",
    compare_over: "Sobra mong pinahahalagahan ang iyong sarili",
  },
  uz: {
    save: "Saqlash", cancel: "Bekor", confirm: "Tasdiqlash", error: "Xato",
    loading: "Yuklanmoqda", done: "Tugallandi", required: "Majburiy", optional: "Ixtiyoriy",
    back: "Orqaga", close: "Yopish", select: "Tanlash", language: "Til",
    login_userId: "Foydalanuvchi nomi", login_password: "Parol",
    login_btn: "Kirish", login_register: "Ro'yxatdan o'tish",
    login_noAccount: "Hisobingiz yo'qmi?",
    login_errorEmpty: "Foydalanuvchi nomi va parolni kiriting.",
    login_errorInvalid: "Foydalanuvchi nomi yoki parol noto'g'ri.",
    reg_title: "Ro'yxatdan o'tish", reg_name: "Ism Familiya", reg_role: "Rol",
    reg_courseName: "Kurs nomi", reg_courseNameRequired: "O'quvchilar kurs nomini kiritishlari shart.", reg_confirmPw: "Parolni tasdiqlash",
    reg_profilePhoto: "Profil rasmi",
    reg_errorRequired: "Foydalanuvchi nomi, parol va ism majburiy.",
    reg_errorPwMatch: "Parollar mos kelmadi.",
    reg_errorPwLength: "Parol kamida 4 ta belgidan iborat bo'lishi kerak.",
    reg_errorDuplicate: "Bu foydalanuvchi nomi allaqachon ishlatilmoqda.",
    role_trainee: "O'quvchi", role_teacher: "O'qituvchi", role_admin: "Administrator",
    nav_gallery: "Galereya", nav_diagnosis: "Reyting", nav_coaching: "AI Murabbiy",
    home_hello: "Salom",
    home_title: "Nimani o'rganmoqchisiz?",
    home_subtitle: "O'qish rejimini tanlang",
    home_theory: "Nazariya",
    home_theoryDesc: "Bugungi dars · OX",
    home_skill: "Mahorat",
    home_skillDesc: "AI · Galereya · Reyting",
    theory_subtitle: "Dars turini tanlang",
    theory_today: "Bugungi dars",
    theory_today_desc: "Har kuni 3 yangi savol",
    theory_review: "Takrorlash",
    theory_ox: "OX o'yini",
    theory_ox_desc: "Eng yuqori to'lqinga erishing",
    theory_difficulty: "Daraja",
    theory_next: "Keyingi",
    theory_submit: "Topshirish",
    theory_finish: "Tugatish",
    theory_correct: "To'g'ri",
    theory_wrong: "Noto'g'ri",
    theory_my_answer: "Mening javobim",
    theory_correct_answer: "To'g'ri javob",
    theory_explanation: "Tushuntirish",
    theory_score_today: "Bugungi ball",
    theory_no_data: "Ma'lumot yo'q",
    theory_must_answer_all: "Barcha savollarga javob bering.",
    theory_submit_error: "Topshirish muvaffaqiyatsiz.",
    theory_pdf_title: "Nazariya tarixi PDF",
    ox_title: "OX o'yini",
    ox_hero: "OX Challenge",
    ox_hero_desc: "Eng yuqori to'lqinni egallang!",
    ox_ranking_title: "Eng yaxshi natijalar",
    ox_ranking_empty: "Hali yozuv yo'q",
    ox_start: "Boshlash",
    ox_accuracy: "Aniqlik",
    ox_resume: "Davom etish",
    ox_start_new: "Boshidan boshlash",
    ox_gameover_title: "SYSTEM FAILURE",
    ox_quit_title: "GAME ABORTED",
    ox_gameover_sub: "Baza vayron qilindi",
    ox_final_wave: "Yakuniy to‘lqin",
    ox_quiz_score: "Viktorina ballari",
    ox_retry: "Qayta urinish",
    ox_exit: "Chiqish",
    gallery_empty: "Hali tahlil natijalari yo'q",
    gallery_upload: "Birinchi AI tashxis olish uchun\npayvandlash suratini yuklang",
    gallery_new: "Yangi tahlil",
    photo_title: "Payvandlash suratini ro'yxatdan o'tkazish",
    photo_front: "Old tomoni", photo_side: "Yon tomoni", photo_back: "Orqa tomoni",
    photo_frontDesc: "Old tomoni (majburiy)",
    photo_sideDesc: "Chok balandligini o'lchash uchun (ixtiyoriy)",
    photo_backDesc: "Orqa tomonni tekshirish uchun (ixtiyoriy)",
    photo_addPhoto: "Rasm qo'shish", photo_changePhoto: "Rasmni almashtirish",
    photo_camera: "Kamera", photo_gallery: "Galereya",
    photo_analyzeBtn: "AI tahlilni boshlash",
    photo_analyzing: "AI payvandlash sifatini tahlil qilmoqda...",
    photo_weldProcess: "Payvandlash jarayoni", photo_weldPosture: "Payvandlash holati",
    photo_weldMaterial: "Material", photo_selfScore: "O'z-o'zini baholash bali",
    photo_thickness: "Material qalinligi (mm)",
    photo_required: "Old tomoni rasm majburiy.",
    photo_scoreError: "Iltimos, 0 dan 100 gacha bal kiriting.",
    photo_selfScoreHint: "O'z-o'zini baholash bali (0~100)",
    diag_aiScore: "AI bali", diag_beadAnalysis: "Chok tahlili",
    diag_defectEval: "Nuqsonlarni baholash", diag_aiReport: "AI Keng qamrovli hisobot",
    diag_heatmap: "Vizual tahlil (Issiqlik xaritasi)",
    diag_selfCompare: "O'z-o'zini baholash taqqoslaması",
    diag_improvements: "AI takomillashtirish takliflari",
    diag_trend: "Kumulyativ tendentsiyalar tahlili", diag_history: "To'liq natijalar tarixi",
    diag_pass: "O'tdi", diag_fail: "O'tmadi", diag_grade: "Daraja",
    diag_defectName: "Nuqson", diag_measured: "O'lchangan", diag_standard: "Standart",
    diag_deduction: "Ayirish", diag_showMarkers: "Nuqson belgilarini ko'rsatish",
    diag_hideMarkers: "Nuqson belgilarini yashirish",
    diag_confidence: "AI ishonch darajasi", diag_avgScore: "O'rtacha ball",
    diag_bestScore: "Eng yuqori ball", diag_totalEvals: "AI baholashlari",
    diag_recentGrade: "So'nggi daraja",
    diag_improvementMulti: "{n} ta baholash asosida shaxsiylashtirilgan o'quv qo'llanma",
    diag_improvementSingle: "Ushbu baholash natijasi asosida o'quv qo'llanma",
    diag_overallVerdict: "Umumiy Hukm", diag_top3: "Top 3 nuqson",
    diag_noDefect: "Nuqson yo'q - A'lo darajadagi payvandlash sifati!",
    bead_width: "Chok eni", bead_height: "Chok balandligi",
    bead_filletSize: "Burchak chok o'lchami", bead_straightness: "To'g'rilik", bead_pitch: "Qadam tekisligi",
    label_process: "Payvandlash jarayoni", label_posture: "Payvandlash holati", label_material: "Material",
    points_suffix: " ball",
    rank_title: "AI Reytingi", rank_subtitle: "Kumulyativ o'rtacha ball asosida",
    rank_total: "Hammasi", rank_weekly: "Haftlik", rank_daily: "Bugun",
    rank_myRank: "Mening reytingim", rank_topRiser: "Eng yuqori ko'tarilgan", rank_topFaller: "Eng ko'p tushgan",
    rank_empty: "Natijalar yo'q", rank_noData: "Hali hech qanday natija ro'yxatdan o'tmagan",
    rank_upload: "yuklash", rank_best: "Eng yuqori", rank_avg: "O'rtacha",
    logout: "Chiqish",
    nav_members: "A'zolar",
    result_notFound: "Natija topilmadi",
    diag_outOf100: "/ 100 ball",
    diag_aiSummary: "AI Keng qamrovli tahlil",
    diag_historyReflected: "({n} ta sessiya tarixi aks ettirilgan)",
    diag_sideAnalyzing: "Yon tomondan rasm tahlil qilinmoqda yoki yuklanmagan",
    diag_backAnalyzing: "Orqa tomondan rasm tahlil qilinmoqda yoki yuklanmagan",
    diag_sideNoData: "Yon tomondan rasm tahlili ma'lumotlari yo'q",
    diag_backNoData: "Orqa tomondan rasm tahlili ma'lumotlari yo'q",
    diag_coordsLoading: "Koordinata ma'lumotlari tayyorlanmoqda",
    diag_noDefectAi: "AI nuqsonlarni aniqlamadi",
    diag_zoomHint: "Bichish: kattalashtirish · Kattalashtirilganida sudrash · Ikki marta tegish: tiklash",
    diag_noPhoto: "Rasm yo'q",
    diag_beadStackTitle: "Chok yig'ish rejimi",
    diag_beadStackMsg: "Chok yig'ish nuqsonlarni baholamaydi.",
    diag_deviation: "og'ish",
    diag_straightnessLabel: "To'g'rilik",
    diag_widthLabel: "Eni",
    diag_beadType: "Chok turi",
    diag_selfScore: "O'z bali",
    diag_atLeast2: "2 yoki undan ortiq baholashdan keyin trend grafigi paydo bo'ladi",
    trend_totalAvg: "{n} ta sessiyaning o'rtachasi",
    trend_skill: "Mahorat tendentsiyasi",
    trend_improved: "▲ Yaxshilandi (+{n} ball)",
    trend_declined: "▼ Pasaydi ({n} ball)",
    trend_vsPrev: "oldingisiga nisbatan",
    trend_currentResult: "Joriy natija",
    adm_deleteTitle: "Natijani o'chirish",
    adm_deleteConfirm: "{name} natijasini o'chirilsinmi?",
    adm_delete: "O'chirish",
    adm_savedTitle: "Saqlandi",
    adm_savedMsg: "Fikr-mulohaza saqlandi.\nAI keyingi tahlildan boshlab ushbu mezonni qo'llaydi.",
    adm_saveFailed: "Fikr-mulohazani saqlash muvaffaqiyatsiz tugadi.",
    adm_networkErr: "Tarmoq xatosi yuz berdi.",
    adm_feedbackTitle: "AI tahlil bo'yicha fikr",
    adm_feedbackDesc: "AI noto'g'ri tahlil qilgan narsani yozing.\nSaqlangan fikr keyingi barcha tahlillarga qo'llaniladi.",
    adm_target: "Maqsad",
    adm_feedbackPlaceholder: "Misol: Spatter deb belgilangan joy aslida overlap.",
    adm_saveSubmit: "Saqlash & AIga qo'llash",
    cm_comments: "Sharhlar",
    cm_empty: "Hali sharhlar yo'q. Birinchi bo'ling!",
    cm_reply: "Javob",
    cm_replyTo: "{name}ga javob",
    cm_inputPlaceholder: "Sharh yozing...",
    cm_replyInputPlaceholder: "{name}ga javob...",
    cm_deleteTitle: "Sharhni o'chirish",
    cm_deleteConfirm: "Ushbu sharhni o'chirilsinmi?",
    cm_addFailed: "Sharh joylashtirilmadi.",
    cm_deleteFailed: "Sharh o'chirilmadi.",
    cm_justNow: "hozirgina",
    cm_minAgo: "{n} daqiqa oldin",
    cm_hourAgo: "{n} soat oldin",
    cm_dayAgo: "{n} kun oldin",
    reg_registrant: "Ro'yxatdan o'tkazuvchi",
    reg_courseUnset: "Kurs tayinlanmagan",
    reg_photoSection: "Rasm yuklash",
    reg_photoHint: "Aniq o'lchov tahlili uchun chok yoniga 30mm ArUco markerini qo'yib suratga oling",
    reg_change: "O'zgartirish",
    reg_plateThickness: "Plastinka qalinligi",
    reg_pipeOuterDiameter: "Quvurning tashqi diametri",
    reg_pipeSpec: "Spetsifikatsiya",
    reg_aiAnalyzingDefault: "AI tahlil qilmoqda...",
    reg_submitBtn: "Yuborish & AI tahlil",
    reg_pipeGuideTitle: "Quvurning tashqi diametri spetsifikatsiyasi",
    reg_pipeHelp: "Nominal o'lchamga teging — tashqi diametr (mm) avtomatik to'ldiriladi.",
    reg_pipeFootnote: "* 250A va 300A uglerod po'lat va zanglamaydigan po'lat quvurlari uchun turli tashqi diametrga ega.",
    reg_photoGuideTitle: "Surat namunalari",
    stage_preparing: "📸 Rasmlar tayyorlanmoqda...",
    stage_uploading: "📤 Serverga yuklanmoqda...",
    stage_detecting: "🔍 Roboflow nuqsonlarni aniqlamoqda...",
    stage_measuring: "📐 O'lchamlar va to'g'rilik hisoblanmoqda...",
    stage_aiAnalyzing: "🤖 {model} chok shaklini tahlil qilmoqda...",
    stage_writingReport: "📝 Keng qamrovli tashxis hisoboti yozilmoqda...",
    stage_finalizing: "✨ Natijalar yakunlanmoqda...",
    camera_webMsg: "Iltimos, kamerani mobil qurilmada ishlating.",
    camera_permNeeded: "Kameraga ruxsat kerak",
    camera_permAllow: "Ruxsat berish",
    camera_arucoInstr: "ArUco markerini yuqori o'ng burchakdagi sariq qo'llanmaga\nmoslang va gorizontal holatda saqlang",
    login_appTitle: "AI Payvandlash Ta'lim Platformasi",
    login_today: "Bugun",
    ai_analysisError: "AI tahlilda xato yuz berdi. Iltimos, qayta urinib ko'ring.",
    photo_reuploadTitle: "Iltimos, rasmni qayta yuklang",
    analysis_errorTitle: "Tahlil xatosi",
    conf_high: "Rasm aniq va o'lchov mezonlari yaxshi kiritilgani uchun yuqori ishonch bilan tahlil qilindi.",
    conf_med: "Aksariyat bandlar aniq tahlil qilindi, lekin ba'zi o'lchov qiymatlari taxminni o'z ichiga olishi mumkin.",
    conf_low: "Rasm aniqligi, yorug'lik yoki suratga olish burchagi ba'zi bandlarning aniqligini cheklaydi. Lineyka bilan rasm yoki turli burchaklardan rasm qo'shish aniqlikni oshiradi.",
    conf_verylow: "Rasm sifati yoki burchagi muammolari tufayli aniq tahlil qilish qiyin bo'ldi. Aniqroq rasmlar va yon, orqa rasmlar hamda lineyka bilan birga olish ishonchni sezilarli darajada oshiradi.",
    compare_accurate: "Aniq o'z-o'zini baholash",
    compare_under: "O'zingizni past baholayapsiz",
    compare_over: "O'zingizni juda yuqori baholayapsiz",
  },
  id: {
    save: "Simpan", cancel: "Batal", confirm: "Konfirmasi", error: "Kesalahan",
    loading: "Memuat", done: "Selesai", required: "Wajib", optional: "Opsional",
    back: "Kembali", close: "Tutup", select: "Pilih", language: "Bahasa",
    login_userId: "Nama Pengguna", login_password: "Kata Sandi",
    login_btn: "Masuk", login_register: "Daftar",
    login_noAccount: "Belum punya akun?",
    login_errorEmpty: "Masukkan nama pengguna dan kata sandi.",
    login_errorInvalid: "Nama pengguna atau kata sandi salah.",
    reg_title: "Pendaftaran", reg_name: "Nama Lengkap", reg_role: "Peran",
    reg_courseName: "Nama Kursus", reg_courseNameRequired: "Peserta pelatihan harus memasukkan nama kursus.", reg_confirmPw: "Konfirmasi Kata Sandi",
    reg_profilePhoto: "Foto Profil",
    reg_errorRequired: "Nama pengguna, kata sandi, dan nama wajib diisi.",
    reg_errorPwMatch: "Kata sandi tidak cocok.",
    reg_errorPwLength: "Kata sandi harus minimal 4 karakter.",
    reg_errorDuplicate: "Nama pengguna sudah digunakan.",
    role_trainee: "Peserta", role_teacher: "Instruktur", role_admin: "Admin",
    nav_gallery: "Galeri", nav_diagnosis: "Peringkat", nav_coaching: "Pelatih AI",
    home_hello: "Halo",
    home_title: "Mau belajar apa?",
    home_subtitle: "Pilih mode belajar",
    home_theory: "Teori",
    home_theoryDesc: "Pelajaran hari ini · OX",
    home_skill: "Skill Up",
    home_skillDesc: "AI · Galeri · Peringkat",
    theory_subtitle: "Pilih jenis pembelajaran",
    theory_today: "Pelajaran Hari Ini",
    theory_today_desc: "3 soal baru setiap hari",
    theory_review: "Ulang",
    theory_ox: "Game OX",
    theory_ox_desc: "Capai wave tertinggi",
    theory_difficulty: "Tingkat",
    theory_next: "Berikutnya",
    theory_submit: "Kirim",
    theory_finish: "Selesai",
    theory_correct: "Benar",
    theory_wrong: "Salah",
    theory_my_answer: "Jawaban saya",
    theory_correct_answer: "Jawaban benar",
    theory_explanation: "Penjelasan",
    theory_score_today: "Skor hari ini",
    theory_no_data: "Tidak ada data",
    theory_must_answer_all: "Mohon jawab semua soal.",
    theory_submit_error: "Pengiriman gagal.",
    theory_pdf_title: "Riwayat Teori PDF",
    ox_title: "Game OX",
    ox_hero: "OX Challenge",
    ox_hero_desc: "Tantang wave tertinggi dengan teori!",
    ox_ranking_title: "Peringkat Wave Tertinggi",
    ox_ranking_empty: "Belum ada catatan",
    ox_start: "Mulai",
    ox_accuracy: "Akurasi",
    ox_resume: "Lanjutkan",
    ox_start_new: "Mulai Baru",
    ox_gameover_title: "SYSTEM FAILURE",
    ox_quit_title: "GAME ABORTED",
    ox_gameover_sub: "Markas telah dihancurkan",
    ox_final_wave: "Wave Akhir",
    ox_quiz_score: "Skor Kuis",
    ox_retry: "Ulangi",
    ox_exit: "Keluar",
    gallery_empty: "Belum ada hasil analisis",
    gallery_upload: "Upload foto las untuk mendapatkan\ndiagnosis AI pertama Anda",
    gallery_new: "Analisis Baru",
    photo_title: "Daftar Foto Las",
    photo_front: "Foto Depan", photo_side: "Foto Samping", photo_back: "Foto Belakang",
    photo_frontDesc: "Depan cap pass (wajib)",
    photo_sideDesc: "Pengukuran tinggi manik (opsional)",
    photo_backDesc: "Inspeksi root pass (opsional)",
    photo_addPhoto: "Tambah Foto", photo_changePhoto: "Ganti Foto",
    photo_camera: "Kamera", photo_gallery: "Galeri",
    photo_analyzeBtn: "Mulai Analisis AI",
    photo_analyzing: "AI sedang menganalisis kualitas las...",
    photo_weldProcess: "Proses Las", photo_weldPosture: "Posisi Las",
    photo_weldMaterial: "Material", photo_selfScore: "Nilai Mandiri",
    photo_thickness: "Ketebalan Material (mm)",
    photo_required: "Foto depan wajib diisi.",
    photo_scoreError: "Masukkan nilai antara 0 dan 100.",
    photo_selfScoreHint: "Nilai mandiri (0~100)",
    diag_aiScore: "Skor AI", diag_beadAnalysis: "Analisis Manik Las",
    diag_defectEval: "Evaluasi Cacat", diag_aiReport: "Laporan Komprehensif AI",
    diag_heatmap: "Analisis Visual (Heatmap)",
    diag_selfCompare: "Perbandingan Penilaian Mandiri",
    diag_improvements: "Saran Peningkatan AI",
    diag_trend: "Analisis Tren Kumulatif", diag_history: "Riwayat Hasil Lengkap",
    diag_pass: "LULUS", diag_fail: "GAGAL", diag_grade: "Nilai",
    diag_defectName: "Cacat", diag_measured: "Terukur", diag_standard: "Standar",
    diag_deduction: "Pengurangan", diag_showMarkers: "Tampilkan Penanda Cacat",
    diag_hideMarkers: "Sembunyikan Penanda Cacat",
    diag_confidence: "Kepercayaan AI", diag_avgScore: "Rata-rata Nilai",
    diag_bestScore: "Nilai Tertinggi", diag_totalEvals: "Evaluasi AI",
    diag_recentGrade: "Nilai Terakhir",
    diag_improvementMulti: "Panduan pelatihan personal berdasarkan {n} evaluasi",
    diag_improvementSingle: "Panduan pelatihan berdasarkan hasil evaluasi ini",
    diag_overallVerdict: "Putusan Keseluruhan", diag_top3: "3 Cacat Teratas",
    diag_noDefect: "Tidak ada cacat - Kualitas las sangat baik!",
    bead_width: "Lebar Manik Las", bead_height: "Tinggi Manik Las",
    bead_filletSize: "Ukuran Kaki Las Sudut", bead_straightness: "Kelurusan", bead_pitch: "Keseragaman Jarak",
    label_process: "Proses Las", label_posture: "Posisi Las", label_material: "Material",
    points_suffix: " poin",
    rank_title: "Peringkat AI", rank_subtitle: "Berdasarkan rata-rata skor kumulatif",
    rank_total: "Semua", rank_weekly: "Mingguan", rank_daily: "Hari ini",
    rank_myRank: "Peringkat Saya", rank_topRiser: "Naik Tertinggi", rank_topFaller: "Turun Terbanyak",
    rank_empty: "Tidak Ada Hasil", rank_noData: "Belum ada hasil yang terdaftar",
    rank_upload: "unggahan", rank_best: "Terbaik", rank_avg: "Rata-rata",
    logout: "Keluar",
    nav_members: "Anggota",
    result_notFound: "Hasil tidak ditemukan",
    diag_outOf100: "/ 100 poin",
    diag_aiSummary: "Analisis Komprehensif AI",
    diag_historyReflected: "(mencerminkan {n} sesi riwayat)",
    diag_sideAnalyzing: "Foto samping sedang dianalisis atau belum diunggah",
    diag_backAnalyzing: "Foto belakang sedang dianalisis atau belum diunggah",
    diag_sideNoData: "Tidak ada data analisis foto samping",
    diag_backNoData: "Tidak ada data analisis foto belakang",
    diag_coordsLoading: "Menyiapkan data koordinat",
    diag_noDefectAi: "AI tidak mendeteksi cacat",
    diag_zoomHint: "Cubit: zoom · Geser saat di-zoom · Ketuk dua kali: reset",
    diag_noPhoto: "Tidak ada foto",
    diag_beadStackTitle: "Mode Bead Stacking",
    diag_beadStackMsg: "Bead stacking tidak mengevaluasi cacat.",
    diag_deviation: "deviasi",
    diag_straightnessLabel: "Kelurusan",
    diag_widthLabel: "Lebar",
    diag_beadType: "Tipe Manik Las",
    diag_selfScore: "Nilai Mandiri",
    diag_atLeast2: "Grafik tren akan muncul setelah 2 evaluasi atau lebih",
    trend_totalAvg: "Rata-rata {n} sesi",
    trend_skill: "Tren Keterampilan",
    trend_improved: "▲ Meningkat (+{n} poin)",
    trend_declined: "▼ Menurun ({n} poin)",
    trend_vsPrev: "vs sebelumnya",
    trend_currentResult: "Hasil saat ini",
    adm_deleteTitle: "Hapus Hasil",
    adm_deleteConfirm: "Hapus hasil milik {name}?",
    adm_delete: "Hapus",
    adm_savedTitle: "Tersimpan",
    adm_savedMsg: "Umpan balik tersimpan.\nAI akan menerapkan standar ini mulai analisis berikutnya.",
    adm_saveFailed: "Gagal menyimpan umpan balik.",
    adm_networkErr: "Terjadi kesalahan jaringan.",
    adm_feedbackTitle: "Umpan Balik Analisis AI",
    adm_feedbackDesc: "Jelaskan apa yang dianalisis salah oleh AI.\nUmpan balik tersimpan akan diterapkan ke semua analisis berikutnya.",
    adm_target: "Target",
    adm_feedbackPlaceholder: "Contoh: Area yang ditandai sebagai spatter sebenarnya adalah overlap.",
    adm_saveSubmit: "Simpan & Terapkan ke AI",
    cm_comments: "Komentar",
    cm_empty: "Belum ada komentar. Jadilah yang pertama!",
    cm_reply: "Balas",
    cm_replyTo: "Balas ke {name}",
    cm_inputPlaceholder: "Tulis komentar...",
    cm_replyInputPlaceholder: "Balas ke {name}...",
    cm_deleteTitle: "Hapus Komentar",
    cm_deleteConfirm: "Hapus komentar ini?",
    cm_addFailed: "Gagal mengirim komentar.",
    cm_deleteFailed: "Gagal menghapus komentar.",
    cm_justNow: "baru saja",
    cm_minAgo: "{n} menit lalu",
    cm_hourAgo: "{n} jam lalu",
    cm_dayAgo: "{n} hari lalu",
    reg_registrant: "Pengirim",
    reg_courseUnset: "Kursus belum diatur",
    reg_photoSection: "Unggah Foto",
    reg_photoHint: "Letakkan ArUco marker 30mm di samping manik las saat memotret untuk analisis dimensi yang akurat",
    reg_change: "Ubah",
    reg_plateThickness: "Ketebalan Pelat",
    reg_pipeOuterDiameter: "Diameter Luar Pipa",
    reg_pipeSpec: "Tabel Spec",
    reg_aiAnalyzingDefault: "AI menganalisis...",
    reg_submitBtn: "Kirim & Analisis AI",
    reg_pipeGuideTitle: "Spec Diameter Luar Pipa",
    reg_pipeHelp: "Ketuk ukuran nominal untuk mengisi otomatis diameter luar (mm).",
    reg_pipeFootnote: "* 250A dan 300A memiliki diameter luar berbeda untuk pipa baja karbon dan stainless steel.",
    reg_photoGuideTitle: "Contoh Foto",
    stage_preparing: "📸 Menyiapkan foto...",
    stage_uploading: "📤 Mengunggah ke server...",
    stage_detecting: "🔍 Roboflow mendeteksi cacat...",
    stage_measuring: "📐 Menghitung dimensi & kelurusan...",
    stage_aiAnalyzing: "🤖 {model} menganalisis bentuk manik...",
    stage_writingReport: "📝 Menulis laporan diagnosis komprehensif...",
    stage_finalizing: "✨ Menyelesaikan hasil...",
    camera_webMsg: "Silakan gunakan kamera di perangkat seluler.",
    camera_permNeeded: "Izin kamera diperlukan",
    camera_permAllow: "Izinkan",
    camera_arucoInstr: "Sejajarkan ArUco marker dengan panduan kuning\ndi kanan atas dan jaga tetap horizontal",
    login_appTitle: "Platform Edukasi Las AI",
    login_today: "Hari ini",
    ai_analysisError: "Terjadi kesalahan saat analisis AI. Silakan coba lagi.",
    photo_reuploadTitle: "Silakan unggah ulang foto",
    analysis_errorTitle: "Kesalahan Analisis",
    conf_high: "Foto jelas dan referensi pengukuran tersertakan dengan baik sehingga dianalisis dengan keandalan tinggi.",
    conf_med: "Sebagian besar item dianalisis dengan jelas, tetapi beberapa nilai pengukuran mungkin mengandung perkiraan.",
    conf_low: "Resolusi foto, pencahayaan, atau sudut pengambilan membatasi akurasi beberapa item. Menambahkan foto dengan penggaris atau foto dari berbagai sudut akan meningkatkan akurasi.",
    conf_verylow: "Analisis akurat sulit dilakukan karena masalah kualitas foto atau sudut. Mengambil foto yang lebih jelas bersama dengan foto samping, belakang, dan penggaris akan sangat meningkatkan keandalan.",
    compare_accurate: "Penilaian diri yang akurat",
    compare_under: "Anda meremehkan diri sendiri",
    compare_over: "Anda menilai diri sendiri terlalu tinggi",
  },
};

interface LanguageContextType {
  lang: LangCode;
  setLang: (code: LangCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "ko",
  setLang: () => {},
  t: (key) => key,
});

const STORAGE_KEY = "app_language";

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<LangCode>("ko");

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY).then((stored) => {
      if (stored && translations[stored as LangCode]) {
        setLangState(stored as LangCode);
      }
    });
  }, []);

  const setLang = useCallback(async (code: LangCode) => {
    setLangState(code);
    await AsyncStorage.setItem(STORAGE_KEY, code);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[lang]?.[key] ?? translations.ko[key] ?? key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
