// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/gallery-screen/Elevated.tsx": () => import("../components/mockups/gallery-screen/Elevated.tsx"),
  "./components/mockups/gallery-screen/Refined.tsx": () => import("../components/mockups/gallery-screen/Refined.tsx")
};
